# Generated by Django 4.0.1 on 2022-02-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_member_designation_remove_member_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
    ]
