# Generated by Django 4.0.1 on 2022-02-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_member_email_remove_member_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='location',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
