# Generated by Django 4.0.1 on 2022-02-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_member_accno_member_beneficiary_name_member_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Passport',
            field=models.ImageField(default='default.jpg', upload_to='passport'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='village',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
