# Generated by Django 4.0.1 on 2022-02-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_member_passport_member_phone_member_village'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='AccNo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='member',
            name='holder',
        ),
        migrations.AddField(
            model_name='member',
            name='Passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Beneficiary_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
