# Generated by Django 4.0.1 on 2022-02-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_member_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
    ]
