# Generated by Django 4.0.1 on 2022-02-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_member_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Beneficiary_name',
            new_name='beneficiary',
        ),
    ]
