# Generated by Django 4.0.1 on 2022-02-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_beneficiary_name_member_beneficiary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Passport_number',
            new_name='passport_number',
        ),
    ]
