# Generated by Django 4.0.1 on 2022-02-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_passport_number_member_passport_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
    ]
