# Generated by Django 4.0.1 on 2022-02-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_member_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Passport',
            new_name='passport',
        ),
    ]
