# Generated by Django 4.0.1 on 2022-02-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_passport_member_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
