# Generated by Django 4.0.1 on 2022-02-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_member_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='acc_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='acc_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='bank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='month_save',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='proof',
            field=models.ImageField(default='default.jpg', upload_to='bank'),
        ),
        migrations.AddField(
            model_name='member',
            name='save_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
