# Generated by Django 4.0.1 on 2022-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_member_acc_number_member_acc_type_member_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='acc_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='bank',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
